/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soft_views;

import soft_class.ProdutosFuncoes;
import soft_class.Produtos;
import java.awt.Component;
import java.awt.Container;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUSTAVO
 */
public class ConsultarProdutos extends javax.swing.JFrame {
    
    private List<Produtos> listaProdutos;

    /**
     * Creates new form Produtos
     */
    public ConsultarProdutos() {
        initComponents();
    }
    
    CadastrarProdutos cadastrarProdutos;
    
    private void chamarCadastarProdutos (){
    if(cadastrarProdutos==null){
        cadastrarProdutos = new CadastrarProdutos ();
        cadastrarProdutos.setVisible(true);
        cadastrarProdutos.setLocationRelativeTo(null);
    }
    else{
        cadastrarProdutos.setVisible(true);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLimpar_Botao = new javax.swing.JToggleButton();
        jPesquisarProdutos_Campo = new javax.swing.JTextField();
        jPesquisarProdutos_Botao = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jFornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jEstoque = new javax.swing.JTextField();
        jNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jNovoProdutos_Botao = new javax.swing.JToggleButton();
        jAlterarProdutos_Botao = new javax.swing.JToggleButton();
        jExcluirProdutos_Botao = new javax.swing.JToggleButton();
        jFecharProdutos_Botao = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();
        jLimpar_Botao1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        jLimpar_Botao.setText("Limpar");
        jLimpar_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpar_BotaoActionPerformed(evt);
            }
        });

        setTitle("Produtos");

        jPesquisarProdutos_Campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarProdutos_CampoActionPerformed(evt);
            }
        });

        jPesquisarProdutos_Botao.setText("Pesquisar");
        jPesquisarProdutos_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarProdutos_BotaoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fornecedor");

        jFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFornecedorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Estoque");

        jEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEstoqueActionPerformed(evt);
            }
        });

        jNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nome");

        jValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Valor");

        jNovoProdutos_Botao.setText("Novo");
        jNovoProdutos_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoProdutos_BotaoActionPerformed(evt);
            }
        });

        jAlterarProdutos_Botao.setText("Alterar");
        jAlterarProdutos_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarProdutos_BotaoActionPerformed(evt);
            }
        });

        jExcluirProdutos_Botao.setText("Excluir");
        jExcluirProdutos_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirProdutos_BotaoActionPerformed(evt);
            }
        });

        jFecharProdutos_Botao.setText("Fechar");
        jFecharProdutos_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFecharProdutos_BotaoActionPerformed(evt);
            }
        });

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Valor", "Estoque"
            }
        ));
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableProdutoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduto);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Codigo");

        jCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigoActionPerformed(evt);
            }
        });

        jLimpar_Botao1.setText("Limpar");
        jLimpar_Botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpar_Botao1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/produtos_botao.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Painel Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jNome)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPesquisarProdutos_Campo)
                                .addGap(18, 18, 18)
                                .addComponent(jPesquisarProdutos_Botao))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jNovoProdutos_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAlterarProdutos_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jExcluirProdutos_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLimpar_Botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(195, 195, 195))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFornecedor)
                                        .addGap(31, 31, 31)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jFecharProdutos_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPesquisarProdutos_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPesquisarProdutos_Botao))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNovoProdutos_Botao)
                    .addComponent(jAlterarProdutos_Botao)
                    .addComponent(jExcluirProdutos_Botao)
                    .addComponent(jLimpar_Botao1))
                .addGap(20, 20, 20)
                .addComponent(jFecharProdutos_Botao)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(239, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(219, 219, 219)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPesquisarProdutos_CampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarProdutos_CampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisarProdutos_CampoActionPerformed

    private void jPesquisarProdutos_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarProdutos_BotaoActionPerformed
        // TODO add your handling code here:
        String dados = jPesquisarProdutos_Campo.getText().toString();
        carregarTudo(dados);
    }//GEN-LAST:event_jPesquisarProdutos_BotaoActionPerformed

    private void jFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFornecedorActionPerformed

    private void jEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEstoqueActionPerformed

    private void jNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeActionPerformed

    private void jValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorActionPerformed

    private void jTableProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMousePressed
        // TODO add your handling code here:
        carregaCamposProdutos();
    }//GEN-LAST:event_jTableProdutoMousePressed

    private void jExcluirProdutos_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirProdutos_BotaoActionPerformed
        // TODO add your handling code here:
        excluirProdutos();
        limparTodosCampos(rootPane);
    }//GEN-LAST:event_jExcluirProdutos_BotaoActionPerformed

    private void jNovoProdutos_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoProdutos_BotaoActionPerformed
        // TODO add your handling code here:
        chamarCadastarProdutos ();
    }//GEN-LAST:event_jNovoProdutos_BotaoActionPerformed

    private void jCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigoActionPerformed

    private void jAlterarProdutos_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarProdutos_BotaoActionPerformed
        // TODO add your handling code here:
        alterarProdutos();
        limparTodosCampos(rootPane);
    }//GEN-LAST:event_jAlterarProdutos_BotaoActionPerformed

    private void jFecharProdutos_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFecharProdutos_BotaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jFecharProdutos_BotaoActionPerformed

    private void jLimpar_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpar_BotaoActionPerformed
        // Limpa os campos:
        limparTodosCampos(rootPane);

    }//GEN-LAST:event_jLimpar_BotaoActionPerformed

    private void jLimpar_Botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpar_Botao1ActionPerformed
        // Limpa os campos:
        limparTodosCampos(rootPane);

    }//GEN-LAST:event_jLimpar_Botao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarProdutos().setVisible(true);
            }
        });
    }
    
    private DefaultTableModel carregaTabela(List<Produtos> listProdutos) {

        String[] colunas = new String[4];
        colunas[0] = "Codigo";
        colunas[1] = "Nome";
        colunas[2] = "Valor";
        colunas[3] = "Estoque";


        DefaultTableModel df = new DefaultTableModel(colunas, 0);

        for (Produtos c : listProdutos) {
            String $codigo = c.getCodigo().toString();
            String $nome = c.getNome().toString();
            String $valor = c.getValor().toString();
            String $estoque = c.getEstoque().toString();
            String[] linhas = new String[4];
            linhas[0] = $codigo;
            linhas[1] = $nome;
            linhas[2] = $valor;
            linhas[3] = $estoque;
            df.addRow(linhas);

        }
        return df;
    }

    private void carregaTabela(DefaultTableModel modelo) {
        jTableProduto.setModel(modelo);
        jTableProduto.setShowGrid(true);
        jTableProduto.getColumnModel().getColumn(0).setPreferredWidth(2);
        jTableProduto.getColumnModel().getColumn(1).setPreferredWidth(10);
    }

    private void carregarTudo(String dados) {
        listaProdutos = ProdutosFuncoes.retornaProdutos(dados);
        DefaultTableModel retDf = new DefaultTableModel();

        retDf = carregaTabela(listaProdutos);
        carregaTabela(retDf);

    }

    private void carregaCamposProdutos() {

        int i = jTableProduto.getSelectedRow();
        if (i < -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Produto");

        } else {
            String codigo = (String) jTableProduto.getValueAt(i, 0);
            Produtos produto = new Produtos();
            produto  = ProdutosFuncoes.retProdutos(codigo);
            
            jCodigo.setText(produto.getCodigo().toString());
            jNome.setText(produto.getNome().toString());
            jValor.setText(produto.getValor().toString());
            jFornecedor.setText(produto.getFornecedor().toString());
            jEstoque.setText(produto.getEstoque().toString());

        }
    }
    
    private void excluirProdutos() {
        
        String codigo = jCodigo.getText();
        String nome = jNome.getText();
        String fornecedor = jFornecedor.getText();
        String estoque = jEstoque.getText();
        String valor = jValor.getText();

        Produtos objProdutos = new Produtos();

        objProdutos.setCodigo(codigo);
        objProdutos.setNome(nome);
        objProdutos.setFornecedor(fornecedor);
        objProdutos.setEstoque(estoque);
        objProdutos.setValor(valor);

        boolean ret = ProdutosFuncoes.excluirProdutos(objProdutos);

        if (ret == true) {
            JOptionPane.showMessageDialog(null, "Produto Excluido com Sucesso");

        }
        
        else if (ret == false){
            JOptionPane.showMessageDialog(null, "ERRO ao Excluir o Produtos");
        }

    }
    
    private void alterarProdutos() {
        
        String codigo = jCodigo.getText();
        String nome = jNome.getText();
        String fornecedor = jFornecedor.getText();
        String estoque = jEstoque.getText();
        String valor = jValor.getText();

        Produtos objProdutos = new Produtos();

        objProdutos.setCodigo(codigo);
        objProdutos.setNome(nome);
        objProdutos.setFornecedor(fornecedor);
        objProdutos.setEstoque(estoque);
        objProdutos.setValor(valor);

        boolean ret = ProdutosFuncoes.alterarProdutos(objProdutos);

        if (ret == true) {
            JOptionPane.showMessageDialog(null, "Produto Alterado com Sucesso");
        }
        
         else if (ret == false){
            JOptionPane.showMessageDialog(null, "ERRO ao Alterar o Produto");
        }        
    }
    
    public void limparTodosCampos(Container container) {

        Component components[] = container.getComponents();
        for (Component component : components) {
            if (component instanceof JFormattedTextField) {
                JFormattedTextField field = (JFormattedTextField) component;
                field.setValue(null);
            } else if (component instanceof JTextField) {
                JTextField field = (JTextField) component;
                field.setText("");
            } else if (component instanceof Container) {
                limparTodosCampos((Container) component);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jAlterarProdutos_Botao;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JTextField jEstoque;
    private javax.swing.JToggleButton jExcluirProdutos_Botao;
    private javax.swing.JToggleButton jFecharProdutos_Botao;
    private javax.swing.JTextField jFornecedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jLimpar_Botao;
    private javax.swing.JToggleButton jLimpar_Botao1;
    private javax.swing.JTextField jNome;
    private javax.swing.JToggleButton jNovoProdutos_Botao;
    private javax.swing.JToggleButton jPesquisarProdutos_Botao;
    private javax.swing.JTextField jPesquisarProdutos_Campo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jValor;
    // End of variables declaration//GEN-END:variables
}
