/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * principal.java
 *
 * Created on 23/08/2012, 15:11:55
 */
package soft_views;

import java.applet.Applet;
import java.applet.AudioClip;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrador
 */
public class Principal extends javax.swing.JFrame {
    
    private RelatorioFuncoes relatorioFuncoes = new RelatorioFuncoes();

    /** Creates new form principal */
    public Principal() {
        initComponents();
        
        try {  
            AudioClip clip = Applet.newAudioClip(new File("C:\\WINDOWS\\Media\\tada.wav").toURL());  
            clip.play();  
        } catch (MalformedURLException ex) {  
            ex.printStackTrace();  
        }
    
    }
    
    ConsultarCliente consultarCliente;
    CadastrarCliente cadastrarCliente;
    ConsultarFornecedor consultarFornecedor;
    CadastrarFornecedor cadastrarFornecedor;
    ConsultarProdutos consultarprodutos;
    RegistrarVendas registrarVendas;
    RelatorioPainel relatorioPainel;
    
    
    private void chamarConsultarCliente (){
    if(consultarCliente==null){
        consultarCliente = new ConsultarCliente ();
        consultarCliente.setVisible(true);
        consultarCliente.setLocationRelativeTo(null);
    }
    else{
        consultarCliente.setVisible(true);
    }
    }
    
    private void chamarCadastarCliente (){
    if(cadastrarCliente==null){
        cadastrarCliente = new CadastrarCliente ();
        cadastrarCliente.setVisible(true);
        cadastrarCliente.setLocationRelativeTo(null);
    }
    else{
        cadastrarCliente.setVisible(true);
    }
    }
    
    private void chamarConsultarFornecedor(){
    if(consultarFornecedor==null){
        consultarFornecedor = new ConsultarFornecedor ();
        consultarFornecedor.setVisible(true);
        consultarFornecedor.setLocationRelativeTo(null);
    }
    else{
        consultarFornecedor.setVisible(true);
    }
    }
    
    private void chamarCadastarFornecedor (){
    if(cadastrarFornecedor==null){
        cadastrarFornecedor = new CadastrarFornecedor ();
        cadastrarFornecedor.setVisible(true);
        cadastrarFornecedor.setLocationRelativeTo(null);
    }
    else{
        cadastrarFornecedor.setVisible(true);
    }
    }
    
    private void chamarConsultarProdutos(){
    if(consultarprodutos==null){
        consultarprodutos = new ConsultarProdutos ();
        consultarprodutos.setVisible(true);
        consultarprodutos.setLocationRelativeTo(null);
    }
    else{
        consultarprodutos.setVisible(true);
    }
    }
    
    private void chamarRegistrarVendas(){
        if(registrarVendas==null){
            registrarVendas = new RegistrarVendas();
            registrarVendas.setVisible(true);
            registrarVendas.setLocationRelativeTo(null);
    }
    else{
        registrarVendas.setVisible(true);
    
        }
    }
    
    private void chamarRelatorioPainel(){
        if(relatorioPainel==null){
            relatorioPainel = new RelatorioPainel();
            relatorioPainel.setVisible(true);
            relatorioPainel.setLocationRelativeTo(null);
    }
    else{
        relatorioPainel.setVisible(true);
    
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jCliente_Botao = new javax.swing.JButton();
        jFornecedor_Botao = new javax.swing.JButton();
        jProdutos_Botao = new javax.swing.JButton();
        jRelatorio_Botao = new javax.swing.JButton();
        jSair_Botao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPedido_Botao1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCliente_Menu = new javax.swing.JMenu();
        jCliente1_Menu = new javax.swing.JMenuItem();
        jFornecedor_Menu = new javax.swing.JMenuItem();
        jProdutos_Menu = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jConsultarCliente_Menu1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jCalculadora_Menu = new javax.swing.JMenuItem();
        jBlocoNotas_Menu = new javax.swing.JMenuItem();
        jSair_Menu = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOFT F5 - Sistema Atualizado");
        setBackground(new java.awt.Color(204, 255, 255));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jCliente_Botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/user_botao.png"))); // NOI18N
        jCliente_Botao.setText("F2 - Cliente");
        jCliente_Botao.setFocusable(false);
        jCliente_Botao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCliente_Botao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCliente_Botao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCliente_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCliente_BotaoActionPerformed(evt);
            }
        });

        jFornecedor_Botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/fornecedor_botao.png"))); // NOI18N
        jFornecedor_Botao.setText("F3 - Fornecedor");
        jFornecedor_Botao.setFocusable(false);
        jFornecedor_Botao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jFornecedor_Botao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jFornecedor_Botao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jFornecedor_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFornecedor_BotaoActionPerformed(evt);
            }
        });

        jProdutos_Botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/produtos_botao.png"))); // NOI18N
        jProdutos_Botao.setText("F4 - Produtos");
        jProdutos_Botao.setFocusable(false);
        jProdutos_Botao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jProdutos_Botao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jProdutos_Botao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jProdutos_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProdutos_BotaoActionPerformed(evt);
            }
        });

        jRelatorio_Botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/relatorio_botao.png"))); // NOI18N
        jRelatorio_Botao.setText("F5 - Relatório");
        jRelatorio_Botao.setFocusable(false);
        jRelatorio_Botao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRelatorio_Botao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jRelatorio_Botao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jRelatorio_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatorio_BotaoActionPerformed(evt);
            }
        });

        jSair_Botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/sair_botao.png"))); // NOI18N
        jSair_Botao.setText("F6 - Sair");
        jSair_Botao.setFocusable(false);
        jSair_Botao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jSair_Botao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jSair_Botao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jSair_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSair_BotaoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/Layout F5.png"))); // NOI18N

        jPedido_Botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/receber.png"))); // NOI18N
        jPedido_Botao1.setText("F6 - Pedido");
        jPedido_Botao1.setFocusable(false);
        jPedido_Botao1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPedido_Botao1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPedido_Botao1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPedido_Botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPedido_Botao1ActionPerformed(evt);
            }
        });

        jCliente_Menu.setText("Cadastro");

        jCliente1_Menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jCliente1_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/user_menu.png"))); // NOI18N
        jCliente1_Menu.setText("Clientes");
        jCliente1_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCliente1_MenuActionPerformed(evt);
            }
        });
        jCliente_Menu.add(jCliente1_Menu);

        jFornecedor_Menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jFornecedor_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/fornecedor_menu.png"))); // NOI18N
        jFornecedor_Menu.setText("Fornecedor");
        jFornecedor_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFornecedor_MenuActionPerformed(evt);
            }
        });
        jCliente_Menu.add(jFornecedor_Menu);

        jProdutos_Menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jProdutos_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/produtos_menu.png"))); // NOI18N
        jProdutos_Menu.setText("Produtos");
        jProdutos_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProdutos_MenuActionPerformed(evt);
            }
        });
        jCliente_Menu.add(jProdutos_Menu);

        jMenuBar1.add(jCliente_Menu);

        jMenu7.setText("Relatórios");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/relatorio_menu.png"))); // NOI18N
        jMenuItem5.setText("Relatório Painel");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/relatorio_menu.png"))); // NOI18N
        jMenu9.setText("Relatórios");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/user_menu.png"))); // NOI18N
        jMenuItem6.setText("Cliente");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/fornecedor_menu.png"))); // NOI18N
        jMenuItem7.setText("Fornecedor");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/produtos_menu.png"))); // NOI18N
        jMenuItem8.setText("Produtos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenu7.add(jMenu9);

        jMenuBar1.add(jMenu7);

        jMenu2.setText("Movimento");

        jConsultarCliente_Menu1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jConsultarCliente_Menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/receber_menu.png"))); // NOI18N
        jConsultarCliente_Menu1.setText("Realizar Pedido");
        jConsultarCliente_Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarCliente_Menu1ActionPerformed(evt);
            }
        });
        jMenu2.add(jConsultarCliente_Menu1);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Utilitários");

        jCalculadora_Menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jCalculadora_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/calculadora_menu.png"))); // NOI18N
        jCalculadora_Menu.setText("Calculadora");
        jCalculadora_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalculadora_MenuActionPerformed(evt);
            }
        });
        jMenu8.add(jCalculadora_Menu);

        jBlocoNotas_Menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jBlocoNotas_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/bloco_de_notas.png"))); // NOI18N
        jBlocoNotas_Menu.setText("Bloco de Notas");
        jBlocoNotas_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlocoNotas_MenuActionPerformed(evt);
            }
        });
        jMenu8.add(jBlocoNotas_Menu);

        jSair_Menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jSair_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/sair_menu.png"))); // NOI18N
        jSair_Menu.setText("Sair");
        jSair_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSair_MenuActionPerformed(evt);
            }
        });
        jMenu8.add(jSair_Menu);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jCliente_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFornecedor_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProdutos_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRelatorio_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSair_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPedido_Botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jCliente_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFornecedor_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jProdutos_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRelatorio_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPedido_Botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSair_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void jCalculadora_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalculadora_MenuActionPerformed
        try {
            // Menu Calculadora:
            Runtime.getRuntime().exec("calc");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCalculadora_MenuActionPerformed

    private void jBlocoNotas_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlocoNotas_MenuActionPerformed
        try {
            // Menu bloco de Notas:
            Runtime.getRuntime().exec("notepad");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBlocoNotas_MenuActionPerformed

    private void jFornecedor_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFornecedor_MenuActionPerformed
        // Menu Fornecedor
        chamarCadastarFornecedor();
    }//GEN-LAST:event_jFornecedor_MenuActionPerformed

    private void jSair_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSair_MenuActionPerformed
        // Menu sair:
        System.exit(0);
    }//GEN-LAST:event_jSair_MenuActionPerformed

    private void jProdutos_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProdutos_MenuActionPerformed
        // Menu Produtos
        chamarConsultarProdutos();
    }//GEN-LAST:event_jProdutos_MenuActionPerformed

    private void jCliente1_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCliente1_MenuActionPerformed
        // Menu Cliente
        chamarCadastarCliente ();
    }//GEN-LAST:event_jCliente1_MenuActionPerformed

    private void jConsultarCliente_Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarCliente_Menu1ActionPerformed
        // TODO add your handling code here:
        chamarRegistrarVendas();
    }//GEN-LAST:event_jConsultarCliente_Menu1ActionPerformed

    private void jSair_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSair_BotaoActionPerformed
        // Botão Sair:
        this.dispose();
    }//GEN-LAST:event_jSair_BotaoActionPerformed

    private void jFornecedor_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFornecedor_BotaoActionPerformed
        // Botão fornecedor
        chamarConsultarFornecedor();
        som();
    }//GEN-LAST:event_jFornecedor_BotaoActionPerformed

    private void jProdutos_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProdutos_BotaoActionPerformed
        // Botão Produto
        chamarConsultarProdutos();
        som();
    }//GEN-LAST:event_jProdutos_BotaoActionPerformed

    private void jCliente_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCliente_BotaoActionPerformed
        //botão cliente
        chamarConsultarCliente ();
        som();
    }//GEN-LAST:event_jCliente_BotaoActionPerformed

    private void jRelatorio_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorio_BotaoActionPerformed
        // TODO add your handling code here:
       chamarRelatorioPainel();
       som();
    }//GEN-LAST:event_jRelatorio_BotaoActionPerformed

    private void jPedido_Botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPedido_Botao1ActionPerformed
        // TODO add your handling code here:
       chamarRegistrarVendas();
       som();
    }//GEN-LAST:event_jPedido_Botao1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
       chamarRelatorioPainel();
       som();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        relatorioFornecedorTodos();
        som();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        relatorioAlunoTodos();
        som();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        relatorioProdutoTodos();
        som();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
     private void som(){
         
         try {
            AudioClip clip = Applet.newAudioClip(new File("C:\\WINDOWS\\Media\\notify.wav").toURL());
            clip.play();
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        }
         
     }
    
    private void relatorioAlunoTodos() {
        int id = 0;
        relatorioFuncoes.relatorio_ClienteTodos(id);
    }
    
    private void relatorioFornecedorTodos() {
        int id = 0;
        relatorioFuncoes.relatorio_FornecedorTodos(id);
    }
    
    private void relatorioProdutoTodos() {
        int idproduto = 0;
        relatorioFuncoes.relatorio_ProdutoTodos(idproduto);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jBlocoNotas_Menu;
    private javax.swing.JMenuItem jCalculadora_Menu;
    private javax.swing.JMenuItem jCliente1_Menu;
    private javax.swing.JButton jCliente_Botao;
    private javax.swing.JMenu jCliente_Menu;
    private javax.swing.JMenuItem jConsultarCliente_Menu1;
    private javax.swing.JButton jFornecedor_Botao;
    private javax.swing.JMenuItem jFornecedor_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JButton jPedido_Botao1;
    private javax.swing.JButton jProdutos_Botao;
    private javax.swing.JMenuItem jProdutos_Menu;
    private javax.swing.JButton jRelatorio_Botao;
    private javax.swing.JButton jSair_Botao;
    private javax.swing.JMenuItem jSair_Menu;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
