/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soft_views;

import java.awt.Component;
import java.awt.Container;
import java.sql.Date;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import soft_class.Cliente;
import soft_class.ClienteFuncoes;
import soft_class.Produtos;
import soft_class.ProdutosFuncoes;
import soft_class.Venda;
import soft_class.VendaFuncoes;

/**
 *
 * @author GUSTAVO
 */
public class RegistrarVendas extends javax.swing.JFrame {
    
    private List<Produtos> listaProdutos;
    private List<Cliente> listaCliente;
    private Venda objVenda = new Venda();
    private VendaFuncoes vendaFuncoes = new VendaFuncoes();

    /**
     * Creates new form RegistrarVendas
     */
    public RegistrarVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPesquisarProdutos_Campo = new javax.swing.JTextField();
        jPesquisarProdutos_Botao = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jTextFieldPesquisa_Cliente = new javax.swing.JTextField();
        jButtonPesquisar_Cliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jQuant = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jDesconto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jValor = new javax.swing.JTextField();
        jFinalizarVenda = new javax.swing.JToggleButton();
        jFecharCliente_Botao = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jEndereco = new javax.swing.JTextField();
        jLimpar = new javax.swing.JToggleButton();

        jPesquisarProdutos_Campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarProdutos_CampoActionPerformed(evt);
            }
        });

        jPesquisarProdutos_Botao.setText("Pesquisar");
        jPesquisarProdutos_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarProdutos_BotaoActionPerformed(evt);
            }
        });

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Valor", "Estoque"
            }
        ));
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableProdutoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduto);

        jTextFieldPesquisa_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisa_ClienteActionPerformed(evt);
            }
        });

        jButtonPesquisar_Cliente.setText("Pesquisar");
        jButtonPesquisar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisar_ClienteActionPerformed(evt);
            }
        });

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cidade", "Endereço"
            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableClienteMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCliente);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Produto:");

        jProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProdutoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Cliente:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Quantidade:");

        jQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuantActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Desconto:");

        jDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDescontoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Valor:");

        jValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorActionPerformed(evt);
            }
        });

        jFinalizarVenda.setText("Finalizar Venda");
        jFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinalizarVendaActionPerformed(evt);
            }
        });

        jFecharCliente_Botao.setText("Cancelar");
        jFecharCliente_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFecharCliente_BotaoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Cliente");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/user_botao.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/produtos_botao.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Produto");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/carrinho_compra.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Módulo de Venda");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Endereço:");

        jEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnderecoActionPerformed(evt);
            }
        });

        jLimpar.setText("Limpar");
        jLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator5)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPesquisarProdutos_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jPesquisarProdutos_Botao))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisa_Cliente)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisar_Cliente))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel12)
                                                .addGap(10, 10, 10)
                                                .addComponent(jQuant))
                                            .addComponent(jCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jFecharCliente_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)))
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPesquisarProdutos_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPesquisarProdutos_Botao))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(4, 4, 4)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar_Cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFecharCliente_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPesquisarProdutos_CampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarProdutos_CampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisarProdutos_CampoActionPerformed

    private void jPesquisarProdutos_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarProdutos_BotaoActionPerformed
        // TODO add your handling code here:
        String dados = jPesquisarProdutos_Campo.getText().toString();
        carregarTudoProduto(dados);
    }//GEN-LAST:event_jPesquisarProdutos_BotaoActionPerformed

    private void jTableProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMousePressed
        // TODO add your handling code here:
        carregaCamposProdutos();
    }//GEN-LAST:event_jTableProdutoMousePressed

    private void jTextFieldPesquisa_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisa_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisa_ClienteActionPerformed

    private void jButtonPesquisar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisar_ClienteActionPerformed
        // TODO add your handling code here:
        String dados = jTextFieldPesquisa_Cliente.getText().toString();
        carregarTudoCliente(dados);
    }//GEN-LAST:event_jButtonPesquisar_ClienteActionPerformed

    private void jTableClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMousePressed
        // TODO add your handling code here:
        carregaCamposClientes();
    }//GEN-LAST:event_jTableClienteMousePressed

    private void jProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProdutoActionPerformed

    private void jQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQuantActionPerformed

    private void jDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDescontoActionPerformed

    private void jFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinalizarVendaActionPerformed
        // TODO add your handling code here:
        inserirVenda();
        cupomFiscal();
    }//GEN-LAST:event_jFinalizarVendaActionPerformed

    private void jFecharCliente_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFecharCliente_BotaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jFecharCliente_BotaoActionPerformed

    private void jValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorActionPerformed

    private void jEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEnderecoActionPerformed

    private void jLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimparActionPerformed
        // TODO add your handling code here:
     limparTodosCampos(rootPane);   
    }//GEN-LAST:event_jLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVendas().setVisible(true);
            }
        });
    }
    
    private void limparDados() {
        jProduto.setText("");
        jValor.setText("");
        jCliente.setText("");
        jEndereco.setText("");
        jQuant.setText("");
        jDesconto.setText("");
    }
    
    private void inserirVenda() {
        
        Date data = new Date(System.currentTimeMillis());
        String cliente = jCliente.getText();
        String produto = jProduto.getText();
        double quantidade = Integer.parseInt (jQuant.getText());
        double desconto = Integer.parseInt (jDesconto.getText());
        double valor = Integer.parseInt (jValor.getText());
        double resultado = valor * quantidade;
        double total = (int) resultado - (resultado * desconto / 100);

        objVenda.setCliente(cliente);
        objVenda.setProduto(produto);
        objVenda.setQuantidade(quantidade);
        objVenda.setDesconto(desconto);
        objVenda.setValor(valor);
        objVenda.setData(data);
        objVenda.setTotal(total);

        objVenda.setIdvenda(vendaFuncoes.inserirVenda(objVenda));
       
    }
    
    private void cupomFiscal() {
        int idvenda = objVenda.getIdvenda();
        RelatorioFuncoes relatorioFuncoes = new RelatorioFuncoes();
        relatorioFuncoes.relatorio_CupomFiscal(idvenda);

    }
    
    //Metódos Cliente
    
    private DefaultTableModel carregaTabelaCliente(List<Cliente> listCliente) {

        String[] colunas = new String[4];
        colunas[0] = "ID";
        colunas[1] = "Nome";
        colunas[2] = "Cidade";
        colunas[3] = "Endereço";

        DefaultTableModel df = new DefaultTableModel(colunas, 0);

        for (Cliente c : listCliente) {
            String $id = c.getId().toString();
            String $nome = c.getNome().toString();
            String $cidade = c.getCidade().toString();
            String $endereco = c.getEndereco().toString();
            String[] linhas = new String[4];
            linhas[0] = $id;
            linhas[1] = $nome;
            linhas[2] = $cidade;
            linhas[3] = $endereco;
            df.addRow(linhas);

        }
        return df;
    }

    private void carregaTabelaCliente(DefaultTableModel modelo) {
        jTableCliente.setModel(modelo);
        jTableCliente.setShowGrid(true);
        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(1); //tamanho da coluna
        jTableCliente.getColumnModel().getColumn(0).setResizable(false);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableCliente.getColumnModel().getColumn(1).setResizable(false);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableCliente.getColumnModel().getColumn(2).setResizable(false);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableCliente.getColumnModel().getColumn(3).setResizable(false);
        
    }

    private void carregarTudoCliente(String dados) {
        listaCliente = ClienteFuncoes.retornaCliente(dados);
        DefaultTableModel retDf = new DefaultTableModel();

        retDf = carregaTabelaCliente(listaCliente);
        carregaTabelaCliente(retDf);

    }
    
    private void carregaCamposClientes() {

        int i = jTableCliente.getSelectedRow();
        if (i < -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente");

        } else {
            String codigo = (String) jTableCliente.getValueAt(i, 0);
            Cliente cliente = new Cliente();
            cliente  = ClienteFuncoes.retCliente(codigo);
            
            jCliente.setText(cliente.getNome().toString());
            jEndereco.setText(cliente.getEndereco().toString());

        }
    }
    
    //Métodos de Produtos
    
    private DefaultTableModel carregaTabelaProduto(List<Produtos> listProdutos) {

        String[] colunas = new String[4];
        colunas[0] = "Codigo";
        colunas[1] = "Nome";
        colunas[2] = "Valor";
        colunas[3] = "Estoque";


        DefaultTableModel df = new DefaultTableModel(colunas, 0);

        for (Produtos c : listProdutos) {
            String $codigo = c.getCodigo().toString();
            String $nome = c.getNome().toString();
            String $valor = c.getValor().toString();
            String $estoque = c.getEstoque().toString();
            String[] linhas = new String[4];
            linhas[0] = $codigo;
            linhas[1] = $nome;
            linhas[2] = $valor;
            linhas[3] = $estoque;
            df.addRow(linhas);

        }
        return df;
    }

    private void carregaTabelaProduto(DefaultTableModel modelo) {
        jTableProduto.setModel(modelo);
        jTableProduto.setShowGrid(true);
        jTableProduto.getColumnModel().getColumn(0).setPreferredWidth(1); //tamanho da coluna
        jTableProduto.getColumnModel().getColumn(0).setResizable(false);
        jTableProduto.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableProduto.getColumnModel().getColumn(1).setResizable(false);
        jTableProduto.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableProduto.getColumnModel().getColumn(2).setResizable(false);
        jTableProduto.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableProduto.getColumnModel().getColumn(3).setResizable(false);
    }

    private void carregarTudoProduto(String dados) {
        listaProdutos = ProdutosFuncoes.retornaProdutos(dados);
        DefaultTableModel retDf = new DefaultTableModel();

        retDf = carregaTabelaProduto(listaProdutos);
        carregaTabelaProduto(retDf);

    }

    private void carregaCamposProdutos() {

        int i = jTableProduto.getSelectedRow();
        if (i < -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Produto");

        } else {
            String codigo = (String) jTableProduto.getValueAt(i, 0);
            Produtos produto = new Produtos();
            produto  = ProdutosFuncoes.retProdutos(codigo);
            
            jProduto.setText(produto.getNome().toString());
            jValor.setText(produto.getValor().toString());

        }
    }
    
    public void limparTodosCampos(Container container) {

        Component components[] = container.getComponents();
        for (Component component : components) {
            if (component instanceof JFormattedTextField) {
                JFormattedTextField field = (JFormattedTextField) component;
                field.setValue(null);
            } else if (component instanceof JTextField) {
                JTextField field = (JTextField) component;
                field.setText("");
            } else if (component instanceof Container) {
                limparTodosCampos((Container) component);
            }
        }
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisar_Cliente;
    private javax.swing.JTextField jCliente;
    private javax.swing.JTextField jDesconto;
    private javax.swing.JTextField jEndereco;
    private javax.swing.JToggleButton jFecharCliente_Botao;
    private javax.swing.JToggleButton jFinalizarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jLimpar;
    private javax.swing.JToggleButton jPesquisarProdutos_Botao;
    private javax.swing.JTextField jPesquisarProdutos_Campo;
    private javax.swing.JTextField jProduto;
    private javax.swing.JTextField jQuant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jTextFieldPesquisa_Cliente;
    private javax.swing.JTextField jValor;
    // End of variables declaration//GEN-END:variables
}
