/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soft_views;

/**
 *
 * @author GUSTAVO
 */
public class RelatorioPainel extends javax.swing.JFrame {
    
    private RelatorioFuncoes relatorioFuncoes = new RelatorioFuncoes();

    /**
     * Creates new form RelatorioPainel
     */
    public RelatorioPainel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonProdutoTodos = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonClienteTodos = new javax.swing.JToggleButton();
        jButtonFornecedorTodos = new javax.swing.JToggleButton();
        jFechar_Botao = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setTitle("Relatório Painel");

        jButtonProdutoTodos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonProdutoTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/produtos_botao.png"))); // NOI18N
        jButtonProdutoTodos.setText("Produto");
        jButtonProdutoTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoTodosActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel15.setText("Painel Relatório");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/relatorio.png"))); // NOI18N

        jButtonClienteTodos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClienteTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/user_botao.png"))); // NOI18N
        jButtonClienteTodos.setText("Cliente");
        jButtonClienteTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteTodosActionPerformed(evt);
            }
        });

        jButtonFornecedorTodos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFornecedorTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft_images/fornecedor_botao.png"))); // NOI18N
        jButtonFornecedorTodos.setText("Fornecedor");
        jButtonFornecedorTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornecedorTodosActionPerformed(evt);
            }
        });

        jFechar_Botao.setText("Fechar");
        jFechar_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFechar_BotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonClienteTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButtonFornecedorTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButtonProdutoTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel15)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jFechar_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFornecedorTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProdutoTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClienteTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFechar_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProdutoTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoTodosActionPerformed
        // TODO add your handling code here:
        relatorioProdutoTodos();
    }//GEN-LAST:event_jButtonProdutoTodosActionPerformed

    private void jButtonClienteTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteTodosActionPerformed
        // TODO add your handling code here:
        relatorioAlunoTodos();
    }//GEN-LAST:event_jButtonClienteTodosActionPerformed

    private void jButtonFornecedorTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornecedorTodosActionPerformed
        // TODO add your handling code here:
        relatorioFornecedorTodos();
    }//GEN-LAST:event_jButtonFornecedorTodosActionPerformed

    private void jFechar_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFechar_BotaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jFechar_BotaoActionPerformed
    
    private void relatorioProdutoTodos() {
        int idproduto = 0;
        relatorioFuncoes.relatorio_ProdutoTodos(idproduto);
    }
    
    private void relatorioFornecedorTodos() {
        int id = 0;
        relatorioFuncoes.relatorio_FornecedorTodos(id);
    }
    
    private void relatorioAlunoTodos() {
        int id = 0;
        relatorioFuncoes.relatorio_ClienteTodos(id);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioPainel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonClienteTodos;
    private javax.swing.JToggleButton jButtonFornecedorTodos;
    private javax.swing.JToggleButton jButtonProdutoTodos;
    private javax.swing.JToggleButton jFechar_Botao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
